Models/ErrorViewModel.cs
namespace tl2_tp6_2024_pnacusse.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/Presupuestos.cs
namespace tl2_tp6_2024_pnacusse.Models
{
    public class Presupuestos
    {
        private int idPresupuesto;
        private string nombreDestinatario;
        private List<PresupuestoDetalle> detalle;
        private DateOnly fechaCreacion;

        public int IdPresupuesto { get => idPresupuesto; set => idPresupuesto = value; }
        public string NombreDestinatario { get => nombreDestinatario; set => nombreDestinatario = value; }
        public List<PresupuestoDetalle> Detalle { get => detalle; set => detalle = value; }
        public DateOnly FechaCreacion { get => FechaCreacion; set => FechaCreacion = value; }

        public Presupuestos(int idPresupuesto, string nombreDestinatario, List<PresupuestoDetalle> detalle, DateOnly fechaCreacion)
        {
            this.idPresupuesto = idPresupuesto;
            this.nombreDestinatario = nombreDestinatario;
            this.detalle = detalle;
            FechaCreacion = fechaCreacion;

        }

        public Presupuestos() { }

        public int getIdPresupuesto() { return idPresupuesto; }


        public void MontoPresupuesto()
        {

        }

        public void MontoPresupuestoConIva()
        {

        }

        public void CantidadProductos()
        {

        }
    }
}

Models/PresupuestosDetalle.cs
namespace tl2_tp6_2024_pnacusse.Models
{
    public class PresupuestoDetalle
    {
        private Productos producto;
        private int cantidad;

        public PresupuestoDetalle(Productos producto, int cantidad)
        {
            this.producto = producto;
            this.cantidad = cantidad;
        }

        public PresupuestoDetalle() { }


        public Productos Producto { get => producto; set => producto = value; }
        public int Cantidad { get => cantidad; set => cantidad = value; }
    }
}

Models/Productos.cs
namespace tl2_tp6_2024_pnacusse.Models
{
    public class Productos
    {
        private int idProducto;
        private string descripcion;
        private int precio;
        public Productos()
        {

        }

        public Productos(int idProducto, string descripcion, int precio)
        {
            IdProducto = idProducto;
            Descripcion = descripcion;
            Precio = precio;

        }
        public int IdProducto { get => idProducto; set => idProducto = value; }
        public string Descripcion { get => descripcion; set => descripcion = value; }
        public int Precio { get => precio; set => precio = value; }
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using tl2_tp6_2024_pnacusse.Models;

namespace tl2_tp6_2024_pnacusse.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/ProductoController.cs
using Microsoft.AspNetCore.Mvc;
using tl2_tp6_2024_pnacusse.Models;
using tl2_tp6_2024_pnacusse.Repositorios;

namespace tl2_tp6_2024_pnacusse.Controllers
{
    public class ProductoController : ControllerBase
    {
        private readonly IProductoRepository _productoRepository;

        public ProductoController(IProductoRepository productoRepository)
        {
            _productoRepository = productoRepository;
        }

        public ActionResult Index()
        {
            var productos = _productoRepository.ListProductos();
            return View(productos);
        }

        private ActionResult View(List<Productos> productos)
        {
            throw new NotImplementedException();
        }

        [HttpGet]
        public ActionResult CreateProducto(Productos producto)
        {
            _productoRepository.CreateProducto(producto);
            return RedirecToAction("Index");
        }

        private ActionResult RedirecToAction(string v)
        {
            throw new NotImplementedException();
        }

        [HttpGet]
        public ActionResult EditProducto(int idProducto)
        {
            return View(_productoRepository.GetProductoById(idProducto));
        }

        private ActionResult View(Productos productos)
        {
            throw new NotImplementedException();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditProducto(Productos producto)
        {
            _productoRepository.UpdateProducto(producto, producto.IdProducto);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult DeleteProducto(int idProducto)
        {
            return View(_productoRepository.GetProductoById(idProducto));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int idProducto)
        {
            _productoRepository.DeletePorId(idProducto);
            return RedirectToAction("Index");
        }


    }

}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Producto/CreateProducto.cshtml
@model tl2_tp6_2024_pnacusse.Models.Productos

@{
    ViewData["Title"] = "Alta de Producto";
}

<h1>Alta de Producto</h1>

<form asp-controller="Producto" asp-action="CreateProducto" method="post">
    <div class="form-group mb-3">
        <label asp-for="Descripcion">Descripción</label>
        <input asp-for="Descripcion" class="form-control" id="descripcion">
    </div>
    <div class="form-group mb-3">
        <label asp-for="Precio">Precio</label>
        <input asp-for="Precio" class="form-control">
    </div>
    <div class="form-group mb-2">
        <button type="submit" class="btn btn-primary">Crear</button>
    </div>
</form>

Views/Producto/DeleteProducto.cshtml
@model tl2_tp6_2024_pnacusse.Models.Productos

@{
    ViewData["Title"] = "Eliminar Producto";
}

<h1>Eliminar Producto</h1>

<p>Esta seguro de que desea elimianr el producto <span class="fw-bold">@Model.Descripcion</span> ?</p>
<form asp-controller="Producto" asp-action="Delete" method="post">
    <input asp-for="IdProducto" type="hidden" value="@Model.IdProducto" />
    <div class="form-group mb-2">
        <button type="submit" class="btn btn-danger">Borrar</button>
    </div>
</form>

<a asp-controller="Producto" asp-action="Index" class="btn btn-secondary">Cancelar</a>

Views/Producto/EditProducto.cshtml
@model tl2_tp6_2024_pnacusse.Models.Productos

@{
    ViewData["Title"] = "Editar Producto";
}

<h1>Modificar de Producto</h1>

<form asp-controller="Producto" asp-action="EditProducto" method="post">
    <div class="form-group mb-3">
        <label asp-for="Descripcion">Descripción</label>
        <input asp-for="Descripcion" class="form-control" id="descripcion" value="@Model.Descripcion">
    </div>
    <div class="form-group mb-3">
        <label asp-for="Precio">Precio</label>
        <input asp-for="Precio" class="form-control" value="@Model.Precio">
    </div>
    <input asp-for="IdProducto" type="hidden" value="@Model.IdProducto" />
    <div class="form-group mb-2">
        <button type="submit" class="btn btn-primary">Modificar</button>
    </div>
</form>

Views/Producto/Index.cshtml
@model IEnumerable<tl2_tp6_2024_pnacusse.Models.Productos>

@{
    ViewData["Title"] = "Index";
}

<h1>Listado de Productos</h1>

<table class="table table-striped table-dark table-bordered align-middle">
    <caption>Lista de productos</caption>
    <thead>
        <tr>
            <th scope="col">Id</th>
            <th scope="col">Descripción</th>
            <th scope="col">Precio</th>
            <th scope="col">Modificar</th>
            <th scope="col">Eliminar</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var producto in Model)
        {
            <tr>
                <td>@producto.IdProducto</td>
                <td>@producto.Descripcion</td>
                <td>@producto.Precio</td>
                <td><a asp-controller="Producto" asp-action="EditProducto" asp-route-idProducto="@producto.IdProducto" class="btn btn-info">Modificar</a></td>
                <td><a asp-controller="Producto" asp-action="DeleteProducto" asp-route-idProducto="@producto.IdProducto" class="btn btn-danger">Borrar</a></td>
            </tr>
        }
    </tbody>
</table>

<a asp-controller="Producto" asp-action="CreateProducto" class="btn btn-dark btn-lg">Alta de producto</a>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - tl2_tp6_2024_pnacusse</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/tl2_tp6_2024_pnacusse.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">tl2_tp6_2024_pnacusse</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - tl2_tp6_2024_pnacusse - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>